package program.rumahsakit;
import db.KoneksiDatabase;
import java.sql.*;

import javax.swing.table.DefaultTableModel;
import login.FormLogin;

/**
 *
 * @author ASUS
 */
public class FormPasien extends javax.swing.JFrame {
    private DefaultTableModel model;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPasien.class.getName());
    public FormPasien() {
        initComponents();
        
        //membuat tabel model
        model = new DefaultTableModel();
        
        //menambahkan table model ke model
        tabelPasien.setModel(model);
        model.addColumn("RM");
        model.addColumn("NAMA");
        model.addColumn("TANGGAL LAHIR");
        model.addColumn("JENIS KELAMIN");
        model.addColumn("ALAMAT");
        //panggil loaddata(dalam kontruktor
        loadData();
    }
    
public void loadData() {
    //menghapus seluruh data
    model.getDataVector().removeAllElements();
    //memberi tahu bahwa data telah kosong
    model.fireTableDataChanged();
    
    try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();
        
        String sql = "SELECT * FROM pasien";
        ResultSet r = s.executeQuery(sql);
        
        while (r.next()) {
            Object[] o = new Object [5];
            o[0] = r.getString("RM");
            o[1] = r.getString("NAMA");
            o[2] = r.getDate("TANGGAL_LAHIR");
            o[3] = r.getString("JENIS_KELAMIN");
            o[4] = r.getString("ALAMAT");
            
            model.addRow(o);
        }
        r.close();
        s.close();
    }   catch (SQLException e) {
            System.out.println("Terjadi Error");
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputRM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputJenisKelamin = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        inputTanggalLahir = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        btnLogout = new javax.swing.JButton();
        Tambah = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelPasien = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI RUMAH SAKIT DR. AMBATAKUM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("INPUT DATA PASIEN");

        jLabel3.setText("No. Rekam Medis");

        jLabel4.setText("Nama Pasien");

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("format = dd/mm/yyyy");

        jLabel7.setText("Jenis Kelamin");

        inputJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAKI LAKI", "PEREMPUAN" }));

        jLabel8.setText("Alamat");

        inputTanggalLahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        inputAlamat.setColumns(20);
        inputAlamat.setRows(5);
        jScrollPane1.setViewportView(inputAlamat);

        btnLogout.setText("KELUAR");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        Tambah.setText("TAMBAH");
        Tambah.addActionListener(this::TambahActionPerformed);

        Ubah.setText("UBAH");
        Ubah.addActionListener(this::UbahActionPerformed);

        Hapus.setText("HAPUS");
        Hapus.addActionListener(this::HapusActionPerformed);

        tabelPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO REKAM MEDIS", "NAMA LENGKAP", "TANGGAL LAHIR", "JENIS KELAMIN", "ALAMAT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelPasien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tambah)
                                .addGap(36, 36, 36)
                                .addComponent(Ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(Hapus))
                            .addComponent(inputRM, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNama)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(inputJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(inputTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(inputJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah)
                    .addComponent(Ubah)
                    .addComponent(Hapus))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        String rm= inputRM.getText();
        String nama = inputNama.getText();
        java.util.Date tanggalLahir = (java.util.Date) inputTanggalLahir.getValue();
        String JenisKelamin = inputJenisKelamin.getSelectedItem().toString();
        String alamat = inputAlamat.getText();

        try {
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "INSERT INTO pasien VALUES (?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, rm);
            p.setString(2, nama);
            p.setDate(3, new java.sql.Date(tanggalLahir.getTime()));
            p.setString(4, JenisKelamin);
            p.setString(5, alamat);
            p.executeUpdate();
            bersihkanForm();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        } finally {
            loadData();
        }

    }//GEN-LAST:event_TambahActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin frmLogin = new FormLogin();
        frmLogin.show();
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed
        // TODO add your handling code here:
                 int i = tabelPasien.getSelectedRow();
        if (i == -1) {
// tidak ada baris terseleksi
            return;
        }
// ambil RM yang terseleksi
        String RM = (String) model.getValueAt(i, 0);
        String NAMA = inputNama.getText();
        java.util.Date TANGGAL_LAHIR = (java.util.Date) inputTanggalLahir.getValue();
        String JENIS_KELAMIN = inputJenisKelamin.getSelectedItem().toString();
        String ALAMAT = inputAlamat.getText();

        try {
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "UPDATE pasien SET NAMA = ?, TANGGAL_LAHIR = ?, JENIS_KELAMIN = ?,ALAMAT =  ? WHERE  RM=  ?";
            try (PreparedStatement p = c.prepareStatement(sql)) {
                p.setString(1, NAMA);
                p.setDate(2, new java.sql.Date(TANGGAL_LAHIR.getTime()));
                p.setString(3, JENIS_KELAMIN);
                p.setString(4, ALAMAT);
                p.setString(5, RM);
                p.executeUpdate();
                bersihkanForm();
                p.close();
            }
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        } finally {
            loadData();
        }

    }//GEN-LAST:event_UbahActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
                 int i = tabelPasien.getSelectedRow();
        if (i == -1) {
// tak ada baris terseleksi
            return;
        }
        String rm= (String) model.getValueAt(i, 0);

        try {
            Connection c = KoneksiDatabase.getKoneksi();
            String sql = "DELETE FROM pasien WHERE RM= ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, rm);
            p.executeUpdate();
            bersihkanForm();
            p.close();
        } catch (SQLException e) {
            System.err.println("Terjadi Error");
        } finally {
            loadData();
        }

    }//GEN-LAST:event_HapusActionPerformed

    private void tabelPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasienMouseClicked
        // TODO add your handling code here:
                int i = tabelPasien.getSelectedRow();
        if (i == -1) {
// tak ada baris terseleksi
            return;
        }
        String rm= (String) model.getValueAt(i, 0);
        inputRM.setText(rm);
        String nama = (String) model.getValueAt(i, 1);
        inputNama.setText(nama);
        java.util.Date tanggalLahir = (java.util.Date) model.getValueAt(i, 2);
        inputTanggalLahir.setValue(tanggalLahir);
        String JenisKelamin = (String) model.getValueAt(i, 3).toString();
        inputJenisKelamin.getSelectedItem();
        String alamat = (String) model.getValueAt(i, 4);
        inputAlamat.setText(alamat);

    }//GEN-LAST:event_tabelPasienMouseClicked

    public void bersihkanForm() {
        inputRM.setText((""));
        inputNama.setText("");
        inputTanggalLahir.setValue(null);
        inputJenisKelamin.getSelectedItem();
        inputAlamat.setText("");

    }                                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPasien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Tambah;
    private javax.swing.JButton Ubah;
    private javax.swing.JButton btnLogout;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JComboBox<String> inputJenisKelamin;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputRM;
    private javax.swing.JFormattedTextField inputTanggalLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelPasien;
    // End of variables declaration//GEN-END:variables
}
